### ISSUE TITLE
Bump Paramiko to version that isn't vulnerable to PYSEC-2022-166

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#312]
### Is your feature request related to a problem? Please describe.

#285 introduced a `requirements.txt` that specifies `paramiko==2.8.1`

This has resulted in a [code scanning alert](https://github.com/atsign-foundation/sshnoports/security/code-scanning/9) and drop in OSSF Scorecard score.

### Describe the solution you'd like

Bump paramiko to at least 2.10.1

Pin dependencies in requirements.txt to SHA256 (take a look at at_python for how we use poetry and pyproject.toml to generate a requirements.txt - the secret sauce is in the update_python_requirements.yml workflow)

Add pip package ecosystem to dependabot.yml, something like:

```
  - package-ecosystem: "pip"
    directory: "/packages/noports_sdk_python"
    schedule:
      interval: "daily"
```

### Describe alternatives you've considered

We could drop paramiko altogether, but I don't think that's practical in environments where we might not have OpenSSH (at a suitably recent version)

### Additional context

https://vulners.com/osv/OSV:PYSEC-2022-166
