### ISSUE TITLE
Build Docker images on release (rather than push to trunk)

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#40]
### Is your feature request related to a problem? Please describe.

Docker images will be (re)built for every push to trunk, and we only have a `latest` tag

### Describe the solution you'd like

Use:

```
on:
  push:
    tags:
      - 'v*.*.*'
```

Instead of:

```
on:
  push:
    branches:
      - trunk
```

And also:

```
      # Extract version for docker tag
      - name: Get version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
```

Then:

```
          tags: |
            atsigncompany/sshnpd:latest
            atsigncompany/sshnpd:release-${{ env.VERSION }}
```
