### ISSUE TITLE
Fwd SSH not working with our dockerhub images

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#475]
[gkc] investigated this on Friday, works for me

### Describe the bug

Need to investigate, the cause is unclear, but the initial ssh connection is failing to authenticate to the dockerhub sshnpd with both pure-dart and /usr/bin/ssh.

### Steps to reproduce

Example docker compose:
```yaml
version: "3.0"
networks:
  default:
services:
  sshnpd:
    network_mode: "host"
    image: atsigncompany/sshnpd:v4.0.0-rc.5
    volumes:
      - ${HOME}/.atsign/keys:/atsign/.atsign/keys
    command: -a "${TO}" -m "${FROM}" -d "${DEVICE}" -s -u -v
    restart: unless-stopped
```

### Expected behavior

It works.
